version: "3.9"
services:
  backend:
    container_name: "vcf-app-backend"
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4242:4242"
    volumes:
      - ./backend:/app/backend
    entrypoint: uvicorn
    command: [ "backend.app:app", "--reload", "--host", "0.0.0.0", "--port", "4242" ]
  frontend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - FLASK_APP=app.py
    ports:
      - "4243:4243"
    volumes:
      - ./frontend:/app
    command: [ "flask", "run", "--host", "0.0.0.0", "--port", "4243"]
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - DB_HOST=postgres
